preload = ~/Pictures/wallpapers/Wolfclan.png
wallpaper = LVDS-1,~/Pictures/wallpapers/Wolfclan.png
wallpaper = HDMI-A-1,~/Pictures/wallpapers/Wolfclan.png
wallpaper = VGA-1,~/Pictures/wallpapers/Wolfclan.png

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
ipc = off

