{den, ...}: {
  den.aspects.workstation = {
    includes = with den.aspects; [
      accounts
      backlight
      blockbench
      boot
      bottles
      browsers
      catppuccin-tools
      dbus
      dconf
      ddcutil
      development
      docker
      ffmpeg
      file-roller
      fonts
      gaming
      gdk-pixbuf
      gcr
      gnome-keyring
      gnome-settings-daemon
      graphics
      gtk
      gvfs
      java
      jetbrains
      kanata
      kdeconnect
      kubernetes
      locale
      location
      media
      mimeapps
      mission-center
      numix-icon-theme
      networking
      nix-registry
      nix-ld
      noctalia
      office
      openssh-hardened
      pipewire
      pointer-cursor
      playerctl
      podman
      podman-compose
      podman-desktop
      power-profiles
      printing
      psd
      qbittorrent
      qt
      rio
      seahorse
      security
      social
      surrealist
      terminal
      thunar
      upower
      wayland-session
      wireshark
      xdg
      xkb
      zed
      ani-cli.noctalia-menu
      # helix.discord-rpc
      helix.languages
      theme.system
    ];
  };
}
